// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/13/2026, 2:15:08 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/mac/Documents/wisekings/partner/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/partner/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/partner/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/partner/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/partner/plugins/**/*.{js,ts,mjs}","/Users/mac/Documents/wisekings/partner/composables/**/*.{js,ts,mjs}","/Users/mac/Documents/wisekings/partner/utils/**/*.{js,ts,mjs}","/Users/mac/Documents/wisekings/partner/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/partner/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/partner/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/wisekings/partner/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;